export const AURA_TYPES = [
  {
    id: 'cosmic',
    name: 'Cosmic Aura',
    emoji: '🌌',
    rarity: 'LEGENDARY',
    weight: 2,
    colors: { primary: '#8b5cf6', secondary: '#06b6d4', accent: '#f0abfc', glow: 'rgba(139,92,246,0.6)' },
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #4f46e5 50%, #06b6d4 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(139,92,246,0.15) 0%, rgba(6,182,212,0.08) 50%, transparent 70%)',
    description: 'You vibrate at frequencies most humans cannot even detect. The universe literally reorganizes itself around your presence. Scientists cannot explain you. Poets have tried and failed.',
    shortDesc: 'Otherworldly. The universe bends for you.',
    traits: ['Deeply intuitive', 'Otherworldly presence', 'Sees patterns others miss', 'Eternal wanderer spirit', 'Time feels different near you'],
    hiddenPower: 'Can manifest things just by thinking about them for exactly 11 days straight',
    redFlag: 'Disappears for 3 weeks and texts "I was in my cosmic era" with zero context or apology',
    greenFlag: 'Makes every single person feel like the most important human in any room',
    animeEnergy: 'The mysterious transfer student who is actually a 1,000-year-old celestial being in disguise',
    auraAnimal: '🐆 Snow Leopard',
    vibeColor: 'Deep Cosmic Violet',
    compatibility: 'Golden Aura & Divine Aura',
    secretThoughts: 'Honestly believe you might be from another dimension. The math just keeps adding up.',
    moodAnalysis: 'Transcendently Unbothered',
    socialVibe: 'Mysteriously Magnetic',
    energyLevel: 97,
    stats: { charisma: 95, mystery: 99, energy: 88, chaos: 45, romance: 72, wisdom: 94 },
    funnyObservations: [
      'You own at least one item that "has a story" — one that takes 45 minutes to fully tell',
      'Strangers tell you their deepest secrets on public transit within 10 minutes',
      'You\'ve had at least 3 "life-changing" realizations in the shower this week alone',
      'Animals trust you more than they trust most humans',
    ],
  },
  {
    id: 'divine',
    name: 'Divine Aura',
    emoji: '✨',
    rarity: 'LEGENDARY',
    weight: 2,
    colors: { primary: '#fbbf24', secondary: '#f9fafb', accent: '#e0f2fe', glow: 'rgba(251,191,36,0.6)' },
    gradient: 'linear-gradient(135deg, #fbbf24 0%, #f9fafb 50%, #7dd3fc 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(251,191,36,0.12) 0%, rgba(249,250,251,0.06) 50%, transparent 70%)',
    description: 'Pure light energy radiates from your core. You carry ancient wisdom in modern form. Some people cry the first time they meet you and cannot explain why. That\'s normal. That\'s you.',
    shortDesc: 'Pure radiant light. Ancient wisdom in modern form.',
    traits: ['Radiantly kind', 'Deeply empathetic', 'Natural healer', 'Soul-level wisdom', 'Protective energy'],
    hiddenPower: 'Can fix someone\'s entire week with a single genuine compliment',
    redFlag: 'Loves everyone so much that setting boundaries feels physically painful',
    greenFlag: 'People feel genuinely safe around you — like, surprisingly safe',
    animeEnergy: 'The angelic character who is too pure for this world but somehow thrives anyway',
    auraAnimal: '🦢 White Swan',
    vibeColor: 'Sacred Gold with White Light',
    compatibility: 'Cosmic Aura & Angel Aura',
    secretThoughts: 'Feel like you have a special mission on earth. You\'re probably right.',
    moodAnalysis: 'Serenely Luminous',
    socialVibe: 'Warm and Magnetically Safe',
    energyLevel: 92,
    stats: { charisma: 91, mystery: 78, energy: 85, chaos: 22, romance: 88, wisdom: 99 },
    funnyObservations: [
      'Babies and dogs lose their minds when you walk in — in the best way',
      'You somehow always have a snack for whoever needs one most',
      'Your hugs have been described as "medically effective" by at least two people',
      'You apologize to furniture when you bump into it',
    ],
  },
  {
    id: 'golden',
    name: 'Golden Aura',
    emoji: '🌟',
    rarity: 'LEGENDARY',
    weight: 3,
    colors: { primary: '#f59e0b', secondary: '#fcd34d', accent: '#fef3c7', glow: 'rgba(245,158,11,0.6)' },
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #fcd34d 50%, #f97316 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(245,158,11,0.15) 0%, rgba(249,115,22,0.08) 50%, transparent 70%)',
    description: 'You are the sun in human form. Every room you enter becomes warmer. Your laugh is infectious. Your energy is addictive. People cancel plans specifically to hang out with you.',
    shortDesc: 'The sun in human form. Warm, radiant, magnetic.',
    traits: ['Infectious charisma', 'Natural leader', 'Radiates joy', 'Effortlessly lovable', 'Naturally abundant'],
    hiddenPower: 'Turns any awkward silence into the most memorable moment of the evening',
    redFlag: 'Needs to be liked by everyone, including people you don\'t even like yourself',
    greenFlag: 'Celebrates other people\'s wins harder than your own wins',
    animeEnergy: 'The main protagonist who wins not by power but because everyone just decides to follow them',
    auraAnimal: '🦁 Golden Lion',
    vibeColor: 'Solar Gold',
    compatibility: 'Main Character & Cosmic Aura',
    secretThoughts: 'Secretly think you\'re the main character. You are absolutely the main character.',
    moodAnalysis: 'Radiantly Confident',
    socialVibe: 'Magnetically Charismatic',
    energyLevel: 94,
    stats: { charisma: 99, mystery: 55, energy: 96, chaos: 40, romance: 85, wisdom: 80 },
    funnyObservations: [
      'Your Spotify playlist has saved at least one party from complete disaster',
      'You\'ve definitely said "this is the best night of my life" at least 6 times this year',
      'People text you specifically when they need to feel better about themselves',
      'You can make a gas station stop feel like an adventure',
    ],
  },
  {
    id: 'shadow',
    name: 'Shadow Aura',
    emoji: '🌑',
    rarity: 'EPIC',
    weight: 5,
    colors: { primary: '#4c1d95', secondary: '#1e1b4b', accent: '#a78bfa', glow: 'rgba(76,29,149,0.7)' },
    gradient: 'linear-gradient(135deg, #1e1b4b 0%, #4c1d95 50%, #312e81 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(76,29,149,0.2) 0%, rgba(30,27,75,0.1) 50%, transparent 70%)',
    description: 'You walk between worlds. Light and dark are equally at home within you. You understand things most people spend entire therapy sessions trying to unpack. Depth is your default setting.',
    shortDesc: 'Between worlds. Unfathomable depth. Quiet power.',
    traits: ['Profoundly deep', 'Emotionally complex', 'Magnetic darkness', 'Perceptive beyond measure', 'Quietly devastating'],
    hiddenPower: 'Can read a person\'s entire psychological history in one conversation without asking a single direct question',
    redFlag: 'Ghosts people mid-connection when it gets too real',
    greenFlag: 'The only person who can talk to someone through their absolute darkest moment',
    animeEnergy: 'The anti-hero with a tragic backstory who everyone suspects is secretly the most powerful one',
    auraAnimal: '🐺 Black Wolf',
    vibeColor: 'Midnight Indigo',
    compatibility: 'Chaos Aura & Cosmic Aura',
    secretThoughts: 'Slightly afraid of how well you understand people\'s darkness. As you should be.',
    moodAnalysis: 'Intensely Introspective',
    socialVibe: 'Dangerously Compelling',
    energyLevel: 83,
    stats: { charisma: 79, mystery: 97, energy: 70, chaos: 62, romance: 80, wisdom: 92 },
    funnyObservations: [
      'Your text messages read like philosophy quotes at 2am',
      'You\'ve "just been thinking" approximately 400 hours more than the average person this year',
      'Your neutral face makes people ask if you\'re okay constantly',
      'You\'ve definitely read Nietzsche on the bus and enjoyed it',
    ],
  },
  {
    id: 'phoenix',
    name: 'Phoenix Aura',
    emoji: '🔥',
    rarity: 'EPIC',
    weight: 5,
    colors: { primary: '#ef4444', secondary: '#f97316', accent: '#fcd34d', glow: 'rgba(239,68,68,0.6)' },
    gradient: 'linear-gradient(135deg, #ef4444 0%, #f97316 50%, #fbbf24 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(239,68,68,0.15) 0%, rgba(249,115,22,0.1) 50%, transparent 70%)',
    description: 'You have been burned down and rebuilt so many times that resilience is now literally in your cellular structure. Every version of you that didn\'t work out made room for this version. This version goes hard.',
    shortDesc: 'Rebuilt from ash. Unstoppable by design.',
    traits: ['Relentless resilience', 'Transformative force', 'Unbreakable spirit', 'Fire in the veins', 'Survivor turned thriver'],
    hiddenPower: 'Gets stronger specifically when things get harder — your pressure response is unmatched',
    redFlag: 'Takes on too much because you\'ve survived everything so far and that feels like a plan',
    greenFlag: 'Rebuilds not just yourself but everyone you care about along the way',
    animeEnergy: 'The character who appears to be defeated in episode 3 and comes back as the most powerful being by episode 24',
    auraAnimal: '🦅 Phoenix Eagle',
    vibeColor: 'Ember Gold to Volcanic Red',
    compatibility: 'Chaos Aura & Sigma Aura',
    secretThoughts: 'Lowkey fear that one day the universe will realize you\'ve had too much character development and make things hard again.',
    moodAnalysis: 'Gloriously Relentless',
    socialVibe: 'Intensely Inspirational',
    energyLevel: 91,
    stats: { charisma: 85, mystery: 72, energy: 98, chaos: 70, romance: 68, wisdom: 86 },
    funnyObservations: [
      'Your "getting back up" story could be a Netflix documentary — minimum 3 seasons',
      'You listen to the same 5 "unstoppable" songs on every comeback era',
      'You\'ve restructured your entire life at least twice before your 30s',
      'Your motivational speeches to yourself in the mirror are genuinely good',
    ],
  },
  {
    id: 'villain',
    name: 'Villain Arc',
    emoji: '🖤',
    rarity: 'EPIC',
    weight: 6,
    colors: { primary: '#7c3aed', secondary: '#dc2626', accent: '#fca5a5', glow: 'rgba(124,58,237,0.6)' },
    gradient: 'linear-gradient(135deg, #1a0a2e 0%, #7c3aed 50%, #dc2626 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(124,58,237,0.2) 0%, rgba(220,38,38,0.08) 50%, transparent 70%)',
    description: 'You have done the inner work, seen the truth, and decided that "nice" was a coping mechanism. You are in your unbothered, unbotherable era. The glow-up is so intense it\'s slightly concerning.',
    shortDesc: 'Unbothered. Upgraded. Slightly concerning energy.',
    traits: ['Unapologetically themselves', 'Strategic mastermind', 'Cuts people off cleanly', 'Coldly brilliant', 'Morally flexible'],
    hiddenPower: 'Can identify exactly what someone wants and give it to them — or withhold it perfectly',
    redFlag: 'Could explain your entire philosophy using only movie villain quotes and those quotes would be completely accurate',
    greenFlag: 'Incredibly loyal to the very small number of people you decide actually deserve it',
    animeEnergy: 'The character who spent 3 arcs being "misunderstood" and has now accepted the title',
    auraAnimal: '🐍 Black Mamba',
    vibeColor: 'Dark Crimson and Void Purple',
    compatibility: 'Shadow Aura & Silent Killer Aura',
    secretThoughts: 'Are you going through something? Or did you evolve? Hard to say. Both, maybe.',
    moodAnalysis: 'Dangerously Calm',
    socialVibe: 'Intimidatingly Composed',
    energyLevel: 89,
    stats: { charisma: 88, mystery: 94, energy: 82, chaos: 76, romance: 60, wisdom: 90 },
    funnyObservations: [
      'Your "soft launch" era is over. The rebrand is aggressive.',
      'You\'ve delivered at least 3 monologues in your head that would honestly be cinematic',
      'The people who underestimated you earlier are watching you very carefully right now',
      'Your playlist title is something like "ascending" or "the chosen one era"',
    ],
  },
  {
    id: 'glitch',
    name: 'Glitch Aura',
    emoji: '⚡',
    rarity: 'RARE',
    weight: 7,
    colors: { primary: '#10b981', secondary: '#06b6d4', accent: '#a7f3d0', glow: 'rgba(16,185,129,0.6)' },
    gradient: 'linear-gradient(135deg, #064e3b 0%, #10b981 50%, #06b6d4 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(16,185,129,0.15) 0%, rgba(6,182,212,0.08) 50%, transparent 70%)',
    description: 'You are running software that was not designed for this reality. You break systems simply by existing near them. You think in non-linear ways that confuse normal people and fascinate everyone else.',
    shortDesc: 'Running unrecognized software. Breaks reality by default.',
    traits: ['Non-linear thinker', 'Breaks patterns effortlessly', 'Digital-native chaos', 'Sees the code behind reality', 'System glitch embodied'],
    hiddenPower: 'Finds loopholes in situations that supposedly have no loopholes',
    redFlag: 'Processes emotions in 6 tabs simultaneously and none of them are loading properly',
    greenFlag: 'Finds solutions nobody else would think of because nobody else thinks the way you do',
    animeEnergy: 'The hacker character who understands the simulation and very politely refuses to follow its rules',
    auraAnimal: '🦎 Electric Gecko',
    vibeColor: 'Terminal Green on Void Black',
    compatibility: 'Chaos Aura & Cosmic Aura',
    secretThoughts: 'Pretty sure you\'ve been running on a different operating system than everyone else. You might be right.',
    moodAnalysis: 'Brilliantly Erratic',
    socialVibe: 'Unpredictably Fascinating',
    energyLevel: 86,
    stats: { charisma: 72, mystery: 88, energy: 84, chaos: 90, romance: 62, wisdom: 83 },
    funnyObservations: [
      'You find the bug in the plan everyone else thought was foolproof',
      'Your notes app is either genius-level or completely unhinged. Sometimes both.',
      'You\'ve started explaining something and watched people\'s expressions go from confused to amazed',
      'Your browser has 47 tabs open right now that are all somehow related',
    ],
  },
  {
    id: 'angel',
    name: 'Angel Aura',
    emoji: '👼',
    rarity: 'RARE',
    weight: 8,
    colors: { primary: '#e0f2fe', secondary: '#fdf4ff', accent: '#fbbf24', glow: 'rgba(224,242,254,0.5)' },
    gradient: 'linear-gradient(135deg, #e0f2fe 0%, #fdf4ff 50%, #fef3c7 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(224,242,254,0.1) 0%, rgba(253,244,255,0.08) 50%, transparent 70%)',
    description: 'You arrived with the specific task of making things better. You cannot physically walk past someone who is struggling without stopping. You are the reason the phrase "guardian angel" exists.',
    shortDesc: 'Born to make things better. Actual guardian angel energy.',
    traits: ['Radiantly gentle', 'Fiercely protective', 'Unconditionally supportive', 'Instinctively nurturing', 'Spiritually elevated'],
    hiddenPower: 'Makes people feel genuinely seen in a way they haven\'t felt in years',
    redFlag: 'Takes on everyone\'s problems so completely that you forget to have your own problems',
    greenFlag: 'Remembers the small things about people that make them feel truly known',
    animeEnergy: 'The healer character who everyone underestimates until the moment they are the only one who can save the day',
    auraAnimal: '🕊️ White Dove',
    vibeColor: 'Celestial Pearl',
    compatibility: 'Divine Aura & Golden Aura',
    secretThoughts: 'You care so deeply it sometimes physically hurts. That\'s your whole thing.',
    moodAnalysis: 'Softly Radiant',
    socialVibe: 'Tenderly Magnetic',
    energyLevel: 88,
    stats: { charisma: 82, mystery: 70, energy: 80, chaos: 18, romance: 92, wisdom: 88 },
    funnyObservations: [
      'You have sent at least one "checking in on you" text that literally changed someone\'s day',
      'People cry around you in a good way with a suspiciously high frequency',
      'Your kindness is so pure that people sometimes Google if you\'re real',
      'You apologize for apologizing too much',
    ],
  },
  {
    id: 'silent_killer',
    name: 'Silent Killer Aura',
    emoji: '🎯',
    rarity: 'RARE',
    weight: 8,
    colors: { primary: '#0d9488', secondary: '#1e293b', accent: '#5eead4', glow: 'rgba(13,148,136,0.6)' },
    gradient: 'linear-gradient(135deg, #0f172a 0%, #0d9488 50%, #1e293b 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(13,148,136,0.15) 0%, rgba(15,23,42,0.1) 50%, transparent 70%)',
    description: 'You say almost nothing and somehow everyone in the room knows exactly who the most important person is. You achieve things quietly, completely, and without explanation. You don\'t announce. You arrive.',
    shortDesc: 'Quiet. Precise. Devastatingly effective.',
    traits: ['Operates in silence', 'Laser precision focus', 'Lets results speak', 'Strategically selective', 'Impossibly self-contained'],
    hiddenPower: 'Can achieve in 2 hours what takes other people 2 weeks — and nobody sees them do it',
    redFlag: 'Communicates in 3-word texts that somehow need a decoder ring',
    greenFlag: 'Comes through when it actually matters in a way that makes everyone else look like they were just rehearsing',
    animeEnergy: 'The side character who barely speaks but is somehow the most powerful person in every scene they appear in',
    auraAnimal: '🦈 Deep Sea Shark',
    vibeColor: 'Dark Teal on Midnight',
    compatibility: 'Shadow Aura & Sigma Aura',
    secretThoughts: 'Have a vague feeling you\'re operating at a level people around you can\'t fully measure. You are.',
    moodAnalysis: 'Coldly Purposeful',
    socialVibe: 'Quietly Terrifying',
    energyLevel: 85,
    stats: { charisma: 76, mystery: 96, energy: 88, chaos: 35, romance: 65, wisdom: 91 },
    funnyObservations: [
      'Your idle face suggests you are three moves ahead in a game others don\'t know they\'re playing',
      'People come to you for the real answer after they\'ve already gotten three other opinions',
      'You\'ve never needed to raise your voice in your entire life. You have not needed to.',
      'Your LinkedIn is either blank or incomprehensibly impressive. No middle ground.',
    ],
  },
  {
    id: 'sigma',
    name: 'Sigma Aura',
    emoji: '🔮',
    rarity: 'UNCOMMON',
    weight: 9,
    colors: { primary: '#6366f1', secondary: '#94a3b8', accent: '#c7d2fe', glow: 'rgba(99,102,241,0.5)' },
    gradient: 'linear-gradient(135deg, #1e1b4b 0%, #6366f1 50%, #94a3b8 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(99,102,241,0.15) 0%, rgba(148,163,184,0.05) 50%, transparent 70%)',
    description: 'You walk your own path. Not as a rebellion — just because you legitimately forgot there were other paths. You are self-reliant to a level that makes therapists gently concerned and philosophers deeply impressed.',
    shortDesc: 'Self-defined. Walks the road not because it\'s less traveled but because you made it.',
    traits: ['Radically self-reliant', 'Internally driven', 'Quietly unconventional', 'Systems thinker', 'Needs no external validation — at all'],
    hiddenPower: 'Can completely reinvent your entire life in 90 days without telling anyone until it\'s done',
    redFlag: 'The phrase "I don\'t need help" is your entire personality sometimes',
    greenFlag: 'Deeply reliable to the rare people who make it into your inner circle',
    animeEnergy: 'The wandering samurai who appears, solves the entire arc, and leaves before anyone can thank them',
    auraAnimal: '🦊 Arctic Fox',
    vibeColor: 'Electric Indigo',
    compatibility: 'Silent Killer & Dark Academia',
    secretThoughts: 'Find most systems and social scripts slightly suspicious. Your skepticism is statistically warranted.',
    moodAnalysis: 'Calmly Autonomous',
    socialVibe: 'Independently Compelling',
    energyLevel: 82,
    stats: { charisma: 73, mystery: 88, energy: 79, chaos: 48, romance: 55, wisdom: 89 },
    funnyObservations: [
      'You\'ve done something impressive completely alone and only mentioned it if asked directly',
      'Your "routine" is something most people would describe as a lifestyle transformation',
      'You give advice exactly once. After that it\'s their problem.',
      'Your search history alternates between deeply philosophical and extremely practical',
    ],
  },
  {
    id: 'main_character',
    name: 'Main Character',
    emoji: '🎬',
    rarity: 'UNCOMMON',
    weight: 9,
    colors: { primary: '#ec4899', secondary: '#f59e0b', accent: '#fce7f3', glow: 'rgba(236,72,153,0.6)' },
    gradient: 'linear-gradient(135deg, #ec4899 0%, #f59e0b 50%, #ef4444 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(236,72,153,0.15) 0%, rgba(245,158,11,0.08) 50%, transparent 70%)',
    description: 'Your life is cinematically structured. Coincidences happen around you at a rate that breaks probability. You walk into rooms to music only you can hear. You are the protagonist and you know it.',
    shortDesc: 'Living in your own movie. The universe agrees.',
    traits: ['Cinematic instincts', 'Narrative awareness', 'Magnetic storytelling', 'Dramatic timing', 'Everything is a scene'],
    hiddenPower: 'Turns ordinary moments into stories that people retell for years',
    redFlag: 'Occasionally forgets that other people are also the main character of their own lives',
    greenFlag: 'Your enthusiasm for your own story is so pure it makes everyone around you want to have one too',
    animeEnergy: 'The protagonist who powers up specifically when the soundtrack kicks in during a fight scene',
    auraAnimal: '🦚 Peacock',
    vibeColor: 'Cinematic Hot Pink',
    compatibility: 'Golden Aura & Hyper Aura',
    secretThoughts: 'You\'ve definitely narrated your own life in your head using a movie trailer voice. Multiple times today.',
    moodAnalysis: 'Gloriously Self-Aware',
    socialVibe: 'Dramatically Captivating',
    energyLevel: 90,
    stats: { charisma: 94, mystery: 68, energy: 92, chaos: 65, romance: 84, wisdom: 72 },
    funnyObservations: [
      'Your mirror conversations are honestly Oscar-worthy monologues',
      'Your walk changes tempo when a good song comes on in public',
      'Your life has had at least 4 distinct "arcs" and you know their names',
      'Something improbably perfect happens to you at least once a week and you just accept it',
    ],
  },
  {
    id: 'chaos',
    name: 'Chaos Aura',
    emoji: '🌪️',
    rarity: 'UNCOMMON',
    weight: 8,
    colors: { primary: '#f97316', secondary: '#8b5cf6', accent: '#fed7aa', glow: 'rgba(249,115,22,0.6)' },
    gradient: 'linear-gradient(135deg, #f97316 0%, #8b5cf6 50%, #ec4899 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(249,115,22,0.15) 0%, rgba(139,92,246,0.08) 50%, transparent 70%)',
    description: 'You are a force of nature with a phone plan. Plans collapse around you not from malice but because your natural orbit is just slightly incompatible with linear cause and effect. Somehow everything turns out fine.',
    shortDesc: 'Force of nature. Destroyer of plans. Somehow always fine.',
    traits: ['Born spontaneous', 'Energy bomb', 'Plans are suggestions', 'Accidentally brilliant', 'Chaotically lovable'],
    hiddenPower: 'Creates the most memorable experiences by completely ignoring the original plan',
    redFlag: 'The phrase "I have an idea" is a mild public safety warning for everyone nearby',
    greenFlag: 'People\'s most legendary stories always start with "so this one time with [you]..."',
    animeEnergy: 'The comic relief character who is actually the most dangerous person in the room when they get serious',
    auraAnimal: '🐉 Chaos Dragon',
    vibeColor: 'Electric Tangerine',
    compatibility: 'Main Character & Glitch Aura',
    secretThoughts: 'Occasionally worry that you are too much. You are exactly the right amount.',
    moodAnalysis: 'Gloriously Unhinged',
    socialVibe: 'Infectiously Chaotic',
    energyLevel: 93,
    stats: { charisma: 90, mystery: 72, energy: 97, chaos: 98, romance: 76, wisdom: 58 },
    funnyObservations: [
      'Your "just 5 minutes" always turns into a 3-hour event minimum',
      'At least two people in your life have a story that starts "I don\'t know how but they..."',
      'Your group chat is the most active one in everyone\'s phone and you know this',
      'You\'ve started a plan, abandoned a plan, accidentally executed the plan better by not having one',
    ],
  },
  {
    id: 'dark_academia',
    name: 'Dark Academia',
    emoji: '📚',
    rarity: 'UNCOMMON',
    weight: 7,
    colors: { primary: '#92400e', secondary: '#7c2d12', accent: '#fde68a', glow: 'rgba(146,64,14,0.5)' },
    gradient: 'linear-gradient(135deg, #1c1917 0%, #92400e 50%, #78350f 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(146,64,14,0.15) 0%, rgba(28,25,23,0.1) 50%, transparent 70%)',
    description: 'You carry the weight of every beautiful, tragic thought ever written. Your aesthetic is candlelight and intellectual crisis. You quote dead philosophers accurately and in context, which should not be as attractive as it is.',
    shortDesc: 'Candles, classics, and quiet devastation.',
    traits: ['Intensely intellectual', 'Aesthetically exacting', 'Melancholically beautiful', 'Obsessively curious', 'Tragically romantic'],
    hiddenPower: 'Can find the exact right quote for any situation from memory, immediately, and it\'s always perfect',
    redFlag: 'Romanticizes suffering just enough to make regular sadness seem glamorous',
    greenFlag: 'Makes everyone around you feel like their thoughts are worth having and sharing',
    animeEnergy: 'The bookish character who turns out to be the most dangerous strategist when provoked',
    auraAnimal: '🦉 Tawny Owl',
    vibeColor: 'Antique Amber',
    compatibility: 'Shadow Aura & Sigma Aura',
    secretThoughts: 'Live about 70% of your life inside your own mind. The other 30% is also kind of in your mind.',
    moodAnalysis: 'Beautifully Melancholic',
    socialVibe: 'Intellectually Seductive',
    energyLevel: 74,
    stats: { charisma: 77, mystery: 91, energy: 65, chaos: 44, romance: 86, wisdom: 95 },
    funnyObservations: [
      'Your coffee order is something that requires at least 4 words minimum',
      'You have strong opinions about books you haven\'t finished and this is fine',
      'Your ideal evening is described using words like "atmospheric" and "contemplative"',
      'You have written at least 200 lines in a journal and called it "just processing"',
    ],
  },
  {
    id: 'alpha',
    name: 'Alpha Aura',
    emoji: '💎',
    rarity: 'UNCOMMON',
    weight: 6,
    colors: { primary: '#1d4ed8', secondary: '#cbd5e1', accent: '#bfdbfe', glow: 'rgba(29,78,216,0.6)' },
    gradient: 'linear-gradient(135deg, #1e3a8a 0%, #1d4ed8 50%, #93c5fd 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(29,78,216,0.15) 0%, rgba(147,197,253,0.05) 50%, transparent 70%)',
    description: 'You have a natural gravitational pull that organizes rooms around you without you trying. You are the person people look to when things are uncertain. You carry yourself like you already know the outcome.',
    shortDesc: 'Natural gravity. Rooms organize around you.',
    traits: ['Natural authority', 'Commanding presence', 'Decisive by default', 'Quiet dominance', 'Leads without announcing it'],
    hiddenPower: 'Can walk into a chaotic situation and have it structured in 8 minutes without raising their voice',
    redFlag: 'Sometimes assumes you know the right answer when you are actually just confident',
    greenFlag: 'Makes decisions when everyone else freezes and the decisions are usually correct',
    animeEnergy: 'The stoic commander character who inspires absolute loyalty without ever asking for it',
    auraAnimal: '🦅 Golden Eagle',
    vibeColor: 'Deep Sapphire',
    compatibility: 'Sigma Aura & Silent Killer',
    secretThoughts: 'Feel most comfortable when you\'re in charge. This is not arrogance. This is accuracy.',
    moodAnalysis: 'Steadily Authoritative',
    socialVibe: 'Naturally Commanding',
    energyLevel: 87,
    stats: { charisma: 88, mystery: 78, energy: 85, chaos: 30, romance: 70, wisdom: 86 },
    funnyObservations: [
      'You\'ve been voluntold into leadership roles you didn\'t ask for and then excelled at them',
      'People you don\'t know well address you more formally than others in the room',
      'Your "I\'ll handle it" face is both reassuring and slightly frightening',
      'You have given at least 2 speeches in your life that were genuinely stirring',
    ],
  },
  {
    id: 'dreamcore',
    name: 'Dreamcore Aura',
    emoji: '🌙',
    rarity: 'COMMON',
    weight: 8,
    colors: { primary: '#818cf8', secondary: '#f0abfc', accent: '#e0f2fe', glow: 'rgba(129,140,248,0.5)' },
    gradient: 'linear-gradient(135deg, #818cf8 0%, #f0abfc 50%, #a5f3fc 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(129,140,248,0.12) 0%, rgba(240,171,252,0.08) 50%, transparent 70%)',
    description: 'You exist in a soft, slightly surreal frequency. Your inner world is so vivid and detailed that reality feels like a public beta. You process everything through feeling and imagery. You dream vividly and remember them in detail.',
    shortDesc: 'Soft reality. Vivid interior world. Pastel frequencies.',
    traits: ['Dream-like perception', 'Surreally creative', 'Emotionally textured', 'Visually attuned', 'Floats slightly above reality'],
    hiddenPower: 'Creates worlds in their mind so complete that they partially exist',
    redFlag: 'Gets so lost in your inner world that important external tasks just sort of stop happening',
    greenFlag: 'Makes everything feel gentle and meaningful — even ordinary Tuesdays',
    animeEnergy: 'The quiet artist character whose sketchbook turns out to contain prophecies',
    auraAnimal: '🦋 Luna Moth',
    vibeColor: 'Iridescent Lavender',
    compatibility: 'Angel Aura & Romantic Aura',
    secretThoughts: 'You have entire alternate lives you live in your daydreams. They are good lives.',
    moodAnalysis: 'Serenely Dreamy',
    socialVibe: 'Softly Enchanting',
    energyLevel: 72,
    stats: { charisma: 74, mystery: 84, energy: 62, chaos: 38, romance: 90, wisdom: 78 },
    funnyObservations: [
      'You zone out in conversations but always return with something weirdly relevant to say',
      'Your aesthetic board is a religious experience for anyone who sees it',
      'You have described at least 3 real places as "giving dreamcore vibes"',
      'Your playlists are titled like chapters of a book nobody has read yet',
    ],
  },
  {
    id: 'romantic',
    name: 'Romantic Aura',
    emoji: '💕',
    rarity: 'COMMON',
    weight: 9,
    colors: { primary: '#f43f5e', secondary: '#fb7185', accent: '#fecdd3', glow: 'rgba(244,63,94,0.5)' },
    gradient: 'linear-gradient(135deg, #f43f5e 0%, #fb923c 50%, #fbbf24 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(244,63,94,0.12) 0%, rgba(251,146,60,0.06) 50%, transparent 70%)',
    description: 'You feel everything deeply and are completely unashamed about it. Love, connection, beauty — these are not soft things to you. They are the entire point. You make people feel cherished in a way that is genuinely rare.',
    shortDesc: 'Feels everything fully. Love is the whole point.',
    traits: ['Deeply feeling', 'Overtly affectionate', 'Beauty-seeking', 'Love languages fluent', 'Wears heart externally'],
    hiddenPower: 'Makes people feel so seen and loved that they become slightly better people after spending time with you',
    redFlag: 'Falls in love with potential and romanticizes situations until you can\'t see reality clearly',
    greenFlag: 'Brings the most genuine, wholehearted love to everyone lucky enough to receive it',
    animeEnergy: 'The romantic lead who writes actual poetry about a sunset and it\'s beautiful and nobody makes fun of them',
    auraAnimal: '🦩 Flamingo',
    vibeColor: 'Rose Sunset Pink',
    compatibility: 'Angel Aura & Dreamcore Aura',
    secretThoughts: 'You have composed full love letters in your head to people you haven\'t even met yet. For the vibe.',
    moodAnalysis: 'Tenderly Warm',
    socialVibe: 'Warmly Enveloping',
    energyLevel: 80,
    stats: { charisma: 86, mystery: 65, energy: 78, chaos: 50, romance: 99, wisdom: 72 },
    funnyObservations: [
      'You have cried at a commercial and felt completely justified about it',
      'Your texting style includes words like "honestly" and "I just feel like" constantly',
      'You make people feel like they\'re the main subject of a very good poem',
      'You\'ve said "this moment is so beautiful" at a gas station at least once',
    ],
  },
  {
    id: 'hyper',
    name: 'Hyper Aura',
    emoji: '⚡',
    rarity: 'COMMON',
    weight: 8,
    colors: { primary: '#eab308', secondary: '#f97316', accent: '#fef9c3', glow: 'rgba(234,179,8,0.6)' },
    gradient: 'linear-gradient(135deg, #eab308 0%, #f97316 50%, #ef4444 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(234,179,8,0.15) 0%, rgba(249,115,22,0.08) 50%, transparent 70%)',
    description: 'You operate on a power setting that has no off button. You do not understand the concept of resting face. You are in motion even when standing still. Your energy is a renewable resource that baffles science.',
    shortDesc: 'No off switch. Perpetual motion. Aggressively alive.',
    traits: ['Boundless energy', 'Physically expressive', 'Talks fast', 'Runs on enthusiasm', 'Life of everything always'],
    hiddenPower: 'Can make any activity a group event through sheer force of enthusiasm',
    redFlag: 'Interrupts to agree enthusiastically approximately 90% of conversations',
    greenFlag: 'Makes everyone feel like they have more energy just by being in the same space as you',
    animeEnergy: 'The enthusiastic support character who secretly trains harder than the actual protagonist',
    auraAnimal: '🐆 Cheetah',
    vibeColor: 'Electric Sunburst Yellow',
    compatibility: 'Golden Aura & Chaos Aura',
    secretThoughts: 'People find your energy exhausting sometimes. Your energy does not care and keeps going.',
    moodAnalysis: 'Electrically Animated',
    socialVibe: 'Infectiously Energetic',
    energyLevel: 99,
    stats: { charisma: 88, mystery: 50, energy: 100, chaos: 82, romance: 72, wisdom: 62 },
    funnyObservations: [
      'You have described something as "amazing" at least 14 times today and you mean it every time',
      'Your resting expression is somehow still excited about something',
      'People ask if you are caffeinated even when you are not',
      'You have started a new hobby in the last 30 days. Probably two.',
    ],
  },
  {
    id: 'crystal',
    name: 'Crystal Aura',
    emoji: '💎',
    rarity: 'COMMON',
    weight: 7,
    colors: { primary: '#7dd3fc', secondary: '#e0f2fe', accent: '#f0f9ff', glow: 'rgba(125,211,252,0.5)' },
    gradient: 'linear-gradient(135deg, #7dd3fc 0%, #a5b4fc 50%, #f0abfc 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(125,211,252,0.12) 0%, rgba(165,180,252,0.06) 50%, transparent 70%)',
    description: 'You are clear, structured, and beautiful. You see the truth in situations with almost uncomfortable clarity. You are precise without being cold. Everything around you becomes more organized simply because you are present.',
    shortDesc: 'Crystal clear. Structured beauty. Uncomfortable truth-telling.',
    traits: ['Crystalline clarity', 'Organized naturally', 'Sees truth cleanly', 'Beautifully precise', 'Quietly powerful'],
    hiddenPower: 'Can identify the actual root cause of a problem in the time it takes others to describe the symptoms',
    redFlag: 'Your standards are so clear and high that some things cannot meet them and never will',
    greenFlag: 'Brings clarity to situations that were confusing everyone else without even trying hard',
    animeEnergy: 'The ice-type character whose precision and power turns out to come from perfect understanding, not coldness',
    auraAnimal: '🦋 Blue Morpho Butterfly',
    vibeColor: 'Clear Sky Blue',
    compatibility: 'Divine Aura & Calm Ocean',
    secretThoughts: 'You have a very specific and correct way things should go. You are usually right about this.',
    moodAnalysis: 'Serenely Clear',
    socialVibe: 'Refreshingly Transparent',
    energyLevel: 78,
    stats: { charisma: 79, mystery: 74, energy: 74, chaos: 28, romance: 76, wisdom: 88 },
    funnyObservations: [
      'Your organizational system is either perfect or completely bespoke — both work',
      'You can spot when something is slightly wrong with a plan before anyone else notices',
      'Your personal space is always cleaner than public spaces — this is not accidental',
      'You have a specific place for most things and know when something is 3 inches off',
    ],
  },
  {
    id: 'calm_ocean',
    name: 'Calm Ocean Aura',
    emoji: '🌊',
    rarity: 'COMMON',
    weight: 8,
    colors: { primary: '#0891b2', secondary: '#67e8f9', accent: '#cffafe', glow: 'rgba(8,145,178,0.5)' },
    gradient: 'linear-gradient(135deg, #0891b2 0%, #06b6d4 50%, #67e8f9 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(8,145,178,0.12) 0%, rgba(103,232,249,0.06) 50%, transparent 70%)',
    description: 'You are the still water that runs deep. You appear calm on the surface in situations that would make others spiral. There is an entire ocean of depth beneath you that most people never see because you protect it so naturally.',
    shortDesc: 'Still on the surface. Infinite depth below.',
    traits: ['Emotionally regulated', 'Deeply calming presence', 'Hidden depths', 'Steady like breathing', 'Understated strength'],
    hiddenPower: 'Can calm a room that is vibrating with tension just by being there and breathing normally',
    redFlag: 'Stays calm so consistently that people sometimes forget to check if you are actually okay',
    greenFlag: 'The person everyone calls when things are genuinely falling apart because you make it manageable',
    animeEnergy: 'The water-type character who everyone underestimates until the moment the ocean becomes a tsunami',
    auraAnimal: '🐋 Blue Whale',
    vibeColor: 'Deep Ocean Blue',
    compatibility: 'Crystal Aura & Angel Aura',
    secretThoughts: 'You are carrying more than you show. People notice this even if they don\'t always ask.',
    moodAnalysis: 'Quietly Profound',
    socialVibe: 'Steadily Grounding',
    energyLevel: 71,
    stats: { charisma: 78, mystery: 82, energy: 65, chaos: 22, romance: 78, wisdom: 88 },
    funnyObservations: [
      'Your "everything is fine" is often genuinely true, which confuses people',
      'You have been called "the calm one" in at least 3 different groups',
      'Your advice is so measured that people write it down',
      'You\'ve stayed calm in a situation where most people would have genuinely panicked',
    ],
  },
  {
    id: 'creative',
    name: 'Creative Genius',
    emoji: '🎨',
    rarity: 'COMMON',
    weight: 7,
    colors: { primary: '#a855f7', secondary: '#f43f5e', accent: '#fbbf24', glow: 'rgba(168,85,247,0.5)' },
    gradient: 'linear-gradient(135deg, #a855f7 0%, #f43f5e 33%, #f59e0b 66%, #10b981 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(168,85,247,0.15) 0%, rgba(244,63,94,0.06) 50%, transparent 70%)',
    description: 'You see connections that simply do not exist for other people until you show them. Your brain runs in full color while everyone else is still calibrating their display. Creation is not something you do — it is what you are.',
    shortDesc: 'Full color brain. Sees what doesn\'t exist yet.',
    traits: ['Perpetually inspired', 'Connection architect', 'Breaks creative rules correctly', 'Sees beauty as information', 'Makes things that did not exist'],
    hiddenPower: 'Can generate 10 original ideas in a single conversation and 3 of them are actually genius',
    redFlag: 'Starts more projects than is technically sustainable for one human person',
    greenFlag: 'Drags the people around them into creative experiences that become core memories',
    animeEnergy: 'The character whose special ability is creating something from nothing that turns out to be the most powerful ability of all',
    auraAnimal: '🦜 Rainbow Macaw',
    vibeColor: 'Full Spectrum Everything',
    compatibility: 'Chaos Aura & Dreamcore Aura',
    secretThoughts: 'You have a project you\'ve been "about to start" for months. It would be extraordinary.',
    moodAnalysis: 'Perpetually Inspired',
    socialVibe: 'Magnetically Creative',
    energyLevel: 84,
    stats: { charisma: 83, mystery: 75, energy: 86, chaos: 70, romance: 80, wisdom: 76 },
    funnyObservations: [
      'You describe your WIPs using the word "just" in a way that dramatically understates them',
      'Your "random idea" at 11pm is often the best idea anyone has had all month',
      'You cannot scroll past something beautiful without stopping to analyze why it works',
      'You have at least 6 things described as your "passion project" simultaneously',
    ],
  },
  {
    id: 'goblin',
    name: 'Goblin Mode',
    emoji: '👺',
    rarity: 'COMMON',
    weight: 5,
    colors: { primary: '#65a30d', secondary: '#854d0e', accent: '#d9f99d', glow: 'rgba(101,163,13,0.5)' },
    gradient: 'linear-gradient(135deg, #365314 0%, #65a30d 50%, #854d0e 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(101,163,13,0.15) 0%, rgba(133,77,14,0.08) 50%, transparent 70%)',
    description: 'You have accepted yourself completely, chaos and all, and you are thriving. You do what you want within the bounds of general decency and you feel great about it. You are fully in your unbothered, unfiltered era.',
    shortDesc: 'Chaotically authentic. No performance. Zero apologies.',
    traits: ['Radically authentic', 'Self-accepting chaos', 'No pretense whatsoever', 'Comfort-first always', 'Gleefully imperfect'],
    hiddenPower: 'So comfortable in their own skin that other people unconsciously relax and become themselves too',
    redFlag: 'The line between "authentic" and "might need to reschedule that appointment" blurs sometimes',
    greenFlag: 'Makes everyone around them feel like they can finally just be themselves without performing',
    animeEnergy: 'The wild card character who everyone writes off and then somehow turns the whole tide of the plot',
    auraAnimal: '🦝 Raccoon',
    vibeColor: 'Forest Cryptid Green',
    compatibility: 'Chaos Aura & NPC Aura',
    secretThoughts: 'You are living your best specific life and not everyone will understand it and you are okay with that.',
    moodAnalysis: 'Chaotically Content',
    socialVibe: 'Genuinely Unfiltered',
    energyLevel: 76,
    stats: { charisma: 72, mystery: 60, energy: 80, chaos: 88, romance: 58, wisdom: 70 },
    funnyObservations: [
      'You eat things in combinations that should not be good but are somehow perfect',
      'Your comfort outfit could not be described as a "look" by any standard definition',
      'You have made choices that cannot be explained and do not need to be',
      'Your internal monologue has a specific unhinged but wholesome quality to it',
    ],
  },
  {
    id: 'npc',
    name: 'NPC Aura',
    emoji: '🤖',
    rarity: 'COMMON',
    weight: 3,
    colors: { primary: '#94a3b8', secondary: '#64748b', accent: '#e2e8f0', glow: 'rgba(148,163,184,0.4)' },
    gradient: 'linear-gradient(135deg, #475569 0%, #94a3b8 50%, #cbd5e1 100%)',
    bgGradient: 'radial-gradient(ellipse at center, rgba(148,163,184,0.12) 0%, rgba(100,116,139,0.06) 50%, transparent 70%)',
    description: 'You are on your routine. It works for you. You are the reliable background character who secretly holds everything together. You are the NPC who, if removed, would cause the entire game to collapse. Do not underestimate this role.',
    shortDesc: 'Background character. Secretly holds everything together.',
    traits: ['Reliably consistent', 'Comfortingly predictable', 'Hidden backbone', 'Quietly essential', 'Background power'],
    hiddenPower: 'If you stopped doing all the small invisible things, everything around you would collapse within 72 hours',
    redFlag: 'Goes through the motions so smoothly that people forget to check if you actually want to be there',
    greenFlag: 'The stability that everyone else leans on, even when they don\'t realize they\'re leaning',
    animeEnergy: 'The background character who turns out to have the most powerful ability in the series — and simply never needed to use it',
    auraAnimal: '🐢 Ancient Tortoise',
    vibeColor: 'Reliable Slate Gray',
    compatibility: 'Calm Ocean & Crystal Aura',
    secretThoughts: 'Secretly have a whole inner world that is infinitely more interesting than your external presentation suggests.',
    moodAnalysis: 'Steadily Neutral',
    socialVibe: 'Dependably Present',
    energyLevel: 62,
    stats: { charisma: 58, mystery: 66, energy: 60, chaos: 20, romance: 60, wisdom: 78 },
    funnyObservations: [
      'You have said "same as usual" to describe your order so many times it is now memory',
      'People describe you as "normal" when recommending you to others. This is secretly the highest praise.',
      'You have a very specific playlist for your very specific commute and it is perfect',
      'You process breaking news 48 hours after everyone else, have perfect analysis, and nobody has asked',
    ],
  },
];

export const getAuraById = (id) => AURA_TYPES.find((a) => a.id === id);

export const RARITY_ORDER = ['LEGENDARY', 'EPIC', 'RARE', 'UNCOMMON', 'COMMON'];
